import { ref, reactive} from "vue"
import { stringToHTML } from "../utils/helper";
import ProductDataService from '../services/ProductDataService';
import ResponseData from "./response";
export function useProduct(){
    const formProduct = reactive({
        'business':'',
        'productType':'',
        'productName':'',
        'productionCapacity':'',
        'uom':'',
        'brandName':'',
        'certification':'',
        'encodedBy': sessionStorage.getItem('userId'),
        'encodedByName': sessionStorage.getItem('name'),
        'encodedDate':'',
        'recStat':'1',
    });
    const columnData = ref([
        {
            title: "",
            formatter: "responsiveCollapse",
            width: 40,
            minWidth: 30,
            hozAlign: "center",
            resizable: false,
            headerSort: false,
        },
  
        // For HTML table
        {
            title: "No",
            minWidth: 100,
            maxWidth: 100,
            field: "id",
            hozAlign: "center",
            headerHozAlign: "center",
            vertAlign: "middle",
            print: false,
            download: false
        },
        {
            title: "Product",
            minWidth: 200,
            responsive: 0,
            field: "productName",
            hozAlign: "center",
            headerHozAlign: "center",
            vertAlign: "middle",
            print: false,
            download: false,
        },
        {
            title: "Production Capacity",
            minWidth: 200,
            field: "productionCapacity",
            hozAlign: "center",
            headerHozAlign: "center",
            vertAlign: "middle",
            print: false,
            download: false,
        },
        {
            title: "UOM",
            minWidth: 200,
            field: "uom",
            hozAlign: "center",
            headerHozAlign: "center",
            vertAlign: "middle",
            print: false,
            download: false,
        },
        {
            title: "Brand Name",
            minWidth: 200,
            field: "brandName",
            hozAlign: "center",
            headerHozAlign: "center",
            vertAlign: "middle",
            print: false,
            download: false,
        },
        {
            title: "Certification",
            minWidth: 200,
            field: "certification",
            hozAlign: "center",
            headerHozAlign: "center",
            vertAlign: "middle",
            print: false,
            download: false,
        },
        // For print format
        {
            title: "No",
            minWidth: 100,
            maxWidth: 100,
            field: "id",
            hozAlign: "center",
            headerHozAlign: "center",
            vertAlign: "middle",
            visible: false,
            print: true,
            download: true,
        },
        {
            title: "Product",
            minWidth: 200,
            responsive: 0,
            field: "productName",
            hozAlign: "center",
            headerHozAlign: "center",
            vertAlign: "middle",
            visible: false,
            print: true,
            download: true,
        },
        {
            title: "Production Capacity",
            minWidth: 200,
            field: "productionCapacity",
            hozAlign: "center",
            headerHozAlign: "center",
            vertAlign: "middle",
            visible: false,
            print: true,
            download: true,
        },
        {
            title: "UOM",
            minWidth: 200,
            field: "uom",
            hozAlign: "center",
            headerHozAlign: "center",
            vertAlign: "middle",
            visible: false,
            print: true,
            download: true,
        },
        {
            title: "Brand Name",
            minWidth: 200,
            field: "brandName",
            hozAlign: "center",
            headerHozAlign: "center",
            visible: false,
            print: true,
            download: true,
        },
        {
            title: "Certification",
            minWidth: 200,
            field: "certification",
            hozAlign: "center",
            headerHozAlign: "center",
            vertAlign: "middle",
            visible: false,
            print: true,
            download: true,
        },
        
    ])
    return {
        formProduct,
        columnData
    }
}